# Generated by Django 5.1.2 on 2024-10-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="columns",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
